#!/usr/bin/env python3
"""Refresh skill collections, marketplace lists, and generated link directories."""
from __future__ import annotations

import argparse
import json
import os
import shutil
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SKILLS_DIR = ROOT / "skills"
DOC_SKILLS_DIR = ROOT / "document-skills"
BUILD_DIR = ROOT / ".build"


def _find_skill_dirs(base_dir: Path) -> list[Path]:
    return sorted(
        [p for p in base_dir.iterdir() if p.is_dir() and (p / "SKILL.md").exists()],
        key=lambda p: p.name,
    )


def _write_list(path: Path, dirs: list[Path]) -> None:
    lines = [str(d.relative_to(ROOT)) for d in dirs]
    content = "\n".join(lines)
    if content:
        content += "\n"
    path.write_text(content, encoding="utf-8")


def _ensure_generated_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)
    marker = path / ".skills-generated"
    if marker.exists():
        return
    if any(path.iterdir()):
        raise RuntimeError(
            f"Refusing to modify non-empty directory without marker: {path}"
        )
    marker.write_text(
        "generated by scripts/refresh_skill_collections.py\n", encoding="utf-8"
    )


def _sync_links(target_dir: Path, sources: list[Path], mode: str) -> None:
    _ensure_generated_dir(target_dir)

    expected = {src.name: src for src in sources}

    # Remove stale entries (but preserve marker)
    for entry in target_dir.iterdir():
        if entry.name == ".skills-generated":
            continue
        if entry.name not in expected:
            if entry.is_symlink() or entry.is_file():
                entry.unlink()
            elif entry.is_dir():
                shutil.rmtree(entry)

    # Create/update links
    for name, src in expected.items():
        link_path = target_dir / name
        if mode == "copy":
            if link_path.exists() or link_path.is_symlink():
                if link_path.is_symlink() or link_path.is_file():
                    link_path.unlink()
                else:
                    shutil.rmtree(link_path)
            shutil.copytree(src, link_path)
            continue

        # symlink mode
        if link_path.is_symlink():
            resolved = link_path.resolve()
            if resolved == src.resolve():
                continue
            link_path.unlink()
        elif link_path.exists():
            if link_path.is_dir():
                shutil.rmtree(link_path)
            else:
                link_path.unlink()

        rel_src = os.path.relpath(src, target_dir)
        link_path.symlink_to(rel_src, target_is_directory=True)


def _update_marketplace(example_paths: list[str], document_paths: list[str]) -> None:
    marketplace_path = ROOT / ".claude-plugin" / "marketplace.json"
    if not marketplace_path.exists():
        return

    data = json.loads(marketplace_path.read_text(encoding="utf-8"))
    plugins = data.get("plugins", [])
    updated = {"example-skills": False, "document-skills": False}

    for plugin in plugins:
        name = plugin.get("name")
        if name == "example-skills":
            plugin["skills"] = [f"./{p}" for p in example_paths]
            updated[name] = True
        elif name == "document-skills":
            plugin["skills"] = [f"./{p}" for p in document_paths]
            updated[name] = True

    if not all(updated.values()):
        missing = [k for k, v in updated.items() if not v]
        raise RuntimeError(f"Missing plugin entries in marketplace.json: {missing}")

    marketplace_path.write_text(
        json.dumps(data, indent=2, sort_keys=False) + "\n", encoding="utf-8"
    )


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Refresh skill collections and generated link directories."
    )
    parser.add_argument(
        "--mode",
        choices=["symlink", "copy"],
        default="copy",
        help="Link strategy for generated skill directories (default: copy).",
    )
    parser.add_argument(
        "--skip-marketplace",
        action="store_true",
        help="Skip updating .claude-plugin/marketplace.json",
    )
    args = parser.parse_args()

    example_skill_dirs = _find_skill_dirs(SKILLS_DIR)
    document_skill_dirs = _find_skill_dirs(DOC_SKILLS_DIR)

    collections_dir = BUILD_DIR / "collections"
    collections_dir.mkdir(parents=True, exist_ok=True)

    _write_list(collections_dir / "example-skills.txt", example_skill_dirs)
    _write_list(collections_dir / "document-skills.txt", document_skill_dirs)

    if not args.skip_marketplace:
        _update_marketplace(
            [str(p.relative_to(ROOT)) for p in example_skill_dirs],
            [str(p.relative_to(ROOT)) for p in document_skill_dirs],
        )

    # Generated link directories in .build/
    _sync_links(BUILD_DIR / "direct" / "example", example_skill_dirs, args.mode)
    _sync_links(BUILD_DIR / "direct" / "document", document_skill_dirs, args.mode)

    _sync_links(BUILD_DIR / "codex" / "skills", example_skill_dirs, args.mode)
    _sync_links(BUILD_DIR / "codex" / "skills-document", document_skill_dirs, args.mode)

    _sync_links(BUILD_DIR / "claude" / "skills", example_skill_dirs, args.mode)
    _sync_links(BUILD_DIR / "claude" / "skills-document", document_skill_dirs, args.mode)

    _sync_links(
        BUILD_DIR / "extensions" / "gemini" / "example-skills" / "skills",
        example_skill_dirs,
        args.mode,
    )
    _sync_links(
        BUILD_DIR / "extensions" / "gemini" / "document-skills" / "skills",
        document_skill_dirs,
        args.mode,
    )

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
